# Generated by Django 3.1 on 2021-02-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BAPMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('part', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=150, null=True)),
                ('part_number', models.TextField()),
                ('link', models.CharField(max_length=500)),
                ('inventory', models.IntegerField(default=0)),
                ('source', models.CharField(default='BuyAutoParts', max_length=100)),
                ('image_url', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DensoMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=50)),
                ('part_number', models.CharField(max_length=150)),
                ('image_url', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SandenMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('engine', models.CharField(max_length=50)),
                ('part_number', models.CharField(max_length=150)),
                ('image_url', models.CharField(max_length=100, null=True)),
                ('url', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ValeoMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('engine', models.IntegerField()),
                ('link', models.CharField(max_length=100)),
                ('inventory', models.IntegerField(default=0)),
                ('source', models.CharField(default='Valeo', max_length=100)),
                ('image_url', models.CharField(max_length=100, null=True)),
                ('engine_fuel', models.CharField(max_length=50)),
                ('ref_new', models.CharField(max_length=50, null=True)),
                ('ref_reman', models.CharField(max_length=50, null=True)),
                ('ref_wo_clutch', models.CharField(max_length=50, null=True)),
                ('clutch_assembly', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17)),
                ('year', models.IntegerField()),
                ('model', models.CharField(max_length=100, null=True)),
                ('make', models.CharField(max_length=100)),
                ('engine', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
